name: 'Setup AMUSE'
description: 'This workflow will setup and install AMUSE'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: 'openmpi'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3.9.0
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install gfortran libopenblas-dev libhdf5-openmpi-dev libgsl0-dev cmake libfftw3-3 libfftw3-dev libmpfr6 libmpfr-dev
        pip install numpy scipy matplotlib docutils mpi4py pytest pytest-timeout
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install amuse
      run: |
        pip install -e .
    - name: build AMUSE framework
      run: |
        make framework
