[project]
name = "amuse-octgrav"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["octgrav/**/*.py"]
exclude = [
    "octgrav/packages",
    "octgrav/support",
    "octgrav/src",
    "octgrav/tests"
    ]
artifacts = ["octgrav/octgrav_cuda_worker"]

[tool.hatch.build.targets.wheel.sources]
"octgrav" = "amuse/community/octgrav"

[tool.pytest.ini_options]
pythonpath = ["octgrav/tests/", "../../../../../tests"]

testpaths = ["octgrav/tests"]

