[project]
name = "amuse-hacs64"
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["hacs64/**/*.py"]
exclude = [
    "hacs64/packages",
    "hacs64/support",
    "hacs64/src",
    "hacs64/tests"
    ]
artifacts = ["hacs64/hacs64_worker"]

[tool.hatch.build.targets.wheel.sources]
"hacs64" = "amuse/community/hacs64"

[tool.pytest.ini_options]
pythonpath = ["hacs64/tests/", "../../../../../tests"]

testpaths = ["hacs64/tests"]
