# This workflow will install AMUSE and SeBa and run SeBa tests with a single version of Python

name: Build and test SeBa

on:
  push:
    paths:
      - src/amuse/community/seba
      - src/amuse/test/suite/codes_tests/test_seba.py
      - .github/workflows/community-seba.yml
  pull_request:
    paths:
      - src/amuse/community/seba
      - src/amuse/test/suite/codes_tests/test_seba.py 
      - .github/workflows/community-seba.yml

jobs:
  build:
    name: 'Build AMUSE framework'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: [ 'openmpi']  # mpich is also an option, doesn't seem to work now
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-amuse
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Build and test SeBa'
        run: |
          make seba.code
      - name: check installation
        run: |
          amusifier --get-amuse-configmk
          pip list
      - name: archive build log
        uses: actions/upload-artifact@v3.1.1
        with:
            name: buildlog
            path: build.log
      - name: test seba
        run: |
          pytest --pyargs amuse.test.suite.codes_tests.test_seba -sv
        env:
          OMPI_MCA_rmaps_base_oversubscribe: 1
          OMPI_MCA_btl_tcp_if_include: lo
